import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Orange Tech +</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Orange Tech +
        </h1>

        <p className={styles.description}>
          Página dos projetos desenvolvidos em React para o bootcamp realizado em parceria entre a <a href="https://dio.me">DIO</a> e o Banco Inter 
        </p>

        <div className={styles.grid}>
          <Link href="/calculadora" className={styles.card}>
            <h2>Calculadora &rarr;</h2>
            <p>Interface gráfica para resolução de equações</p>
          </Link>

          <Link href="/githubWiki" className={styles.card}>
            <h2>Github Wiki &rarr;</h2>
            <p>Busca de repositório no Github</p>
          </Link>

          <Link href="/cadastroDIO" className={styles.card}>
            <h2>Cadastro DIO &rarr;</h2>
            <p>Clone da tela de cadastro da DIO</p>
          </Link>

          <Link href="/login" className={styles.card}>
            <h2>Tela de Login &rarr;</h2>
            <p>Exemplo de tela de login com validação</p>
          </Link>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
